USE `bilddb`;

ALTER TABLE pictures
ADD COLUMN creation_date TIMESTAMP DEFAULT (CURRENT_TIMESTAMP) NOT NULL

ALTER TABLE pictures
ADD COLUMN longitude DECIMAL NULL;

ALTER TABLE pictures
ADD COLUMN latitude DECIMAL NULL;
